//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDDISTRIBUCIONEntities : DbContext
    {
        public BDDISTRIBUCIONEntities()
            : base("name=BDDISTRIBUCIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<paisdepa> paisdepa { get; set; }
        public virtual DbSet<RUTA> RUTA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Pago> Tipo_Pago { get; set; }
        public virtual DbSet<TIPONEGOCIO> TIPONEGOCIO { get; set; }
        public virtual DbSet<TIPOPRE> TIPOPRE { get; set; }
        public virtual DbSet<ACCESO> ACCESO { get; set; }
    
        public virtual int NSP_INSERT_TIPONEGOCIO(string cODEMPRESA, string cODIGO, string dESCRIPCION)
        {
            var cODEMPRESAParameter = cODEMPRESA != null ?
                new ObjectParameter("CODEMPRESA", cODEMPRESA) :
                new ObjectParameter("CODEMPRESA", typeof(string));
    
            var cODIGOParameter = cODIGO != null ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_INSERT_TIPONEGOCIO", cODEMPRESAParameter, cODIGOParameter, dESCRIPCIONParameter);
        }
    }
}
